# This workflow runs main.py and but won't post updates on Twitter (for testing purposes)

name: Update (without tweeting)

on:
  workflow_dispatch: # Runs only manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content # Checkout the repository content to GitHub runner
      uses: actions/checkout@v2
    - name: setup python # Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # The script actually runs fine with Python 3.8
    - name: install pip # Install pip
      run: |
        python -m pip install --upgrade pip
    - name: install requirements # Install external modules
      run: |
        pip3 install -r requirements.txt
    - name: execute py script # Run the script to fetch the latest data
      run: |
        python main.py -no-tweet -no-instagram
      env: # API KEYs are passed as environment variables. For more info https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} 
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        INSTAGRAM_ACCOUNT_USERNAME: ${{ secrets.INSTAGRAM_ACCOUNT_USERNAME }}
        INSTAGRAM_ACCOUNT_PASSWORD: ${{ secrets.INSTAGRAM_ACCOUNT_PASSWORD }}
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
    - name: Commit changes # Commit changes to the master branch
      run: |
        git config --global user.name 'marco97pa'
        git config --global user.email 'marco97pa@live.it'
        git add .
        git commit -m "Updated data.yaml"
        git push
